AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: ''
      FunctionName: my-CF-Lambda
      Handler: index.handler
      Architectures:
        - x86_64
      Code:
        S3Bucket: my.lambda.deployment.bucket
        S3Key: main.zip
      MemorySize: 128
      Role: arn:aws:iam::876053156279:role/lambda-ex
      Runtime: python3.8
      Timeout: 3
      TracingConfig:
        Mode: PassThrough
      EphemeralStorage:
        Size: 512